
name: TOML/Mitre Validation
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #https://github.com/actions/setup-python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' 
      - run: pip install --upgrade pip
      - run: pip install requests
      - run:
          python development/validation.py
      - run:
          python development/mitre.py