
name: Elastic Sync
on:
  push:
    path:
      '**.toml'
  workflow_dispatch:
jobs:
  elastic-detections-update:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4' 
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #https://github.com/marketplace/actions/changed-files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}

        run: 
          - run: pip install --upgrade pip
          - run: pip install requests
          - run:
              python development/update_alert.py

   
